version: '3.8'

services:
  petition-db:
    image: postgres:latest
    env_file:
      - .env.development.local
    volumes: 
      - petition-db-data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    

volumes:
  petition-db-data: {}
